version: "3.9"

services:

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  auth:
    image: 704593926034.dkr.ecr.ap-south-1.amazonaws.com/streamingapp/auth:latest
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      PORT: 3001
      MONGO_URI: mongodb://mongo:27017/streamingapp
      JWT_SECRET: changeme
      CLIENT_URLS: http://frontend:3000
    ports:
      - "3001:3001"

  streaming:
    image: 704593926034.dkr.ecr.ap-south-1.amazonaws.com/streamingapp/streaming:latest
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      PORT: 3002
      MONGO_URI: mongodb://mongo:27017/streamingapp
      STREAMING_PUBLIC_URL: http://streaming:3002
    ports:
      - "3002:3002"

  admin:
    image: 704593926034.dkr.ecr.ap-south-1.amazonaws.com/streamingapp/admin:latest
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      PORT: 3003
      MONGO_URI: mongodb://mongo:27017/streamingapp
    ports:
      - "3003:3003"

  chat:
    image: 704593926034.dkr.ecr.ap-south-1.amazonaws.com/streamingapp/chat:latest
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      PORT: 3004
      MONGO_URI: mongodb://mongo:27017/streamingapp
    ports:
      - "3004:3004"

  frontend:
    image: 704593926034.dkr.ecr.ap-south-1.amazonaws.com/streamingapp/frontend:latest
    restart: unless-stopped
    depends_on:
      - auth
      - streaming
      - admin
      - chat
    ports:
      - "3000:80"

volumes:
  mongo-data: